language: python
os:
- linux
dist: xenial
python:
- '3.8'
notifications:
  email:
    recipients:
    - ashikkumar23@gmail.com
    on_success: always
    on_failure: always
install:
- pip install -r tests/requirements.txt
script:
- cd tests
- pytest -vv --gherkin-terminal-reporter --reruns 1 --reruns-delay 1 --tags="automated"
